const wordSets = [
  // 'adjectives',
  // 'adverbs',
  'animals',
  'common',
  // 'compounds',
  // 'cats',
  // 'dinosaurs',
  // 'dogs',
  'encouragement',
  // 'fabrics',
  // 'flowers',
  'fruits',
  // 'gemstones',
  'genres',
  // 'horses',
  'instruments',
  // 'knots',
  // 'menu',
  'moods',
  // 'metals',
  'nouns',
  // 'objects',
  // 'occupations',
  // 'prepositions',
  'rhymeless',
  'sports',
  // 'vegetables',
  // 'verbs',
  // 'verbs_past',
  'weather',
  // 'wrestlers',
];

export default wordSets;
